artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/16bj4Wz-rvcxwhuyO1SIVGsfZg928_iFH/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/new_model.h5
  updated_base_model_path: artifacts/prepare_base_model/new_model_updated.h5
  new_model_path : artifacts/prepare_base_model/new_model.h5
  updated_new_model_path: artifacts/prepare_base_model/new_model_updated.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/new_model.h5
  new_trained_model_path: artifacts/training/new_model.h5
  